---
title: "Create Figure 2 - Habitats and Assemblages"
output: html_document
date: "2025-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r create count data}
#climatic zone counts
climatic_zone <- data %>% 
  count(climatic_zone) %>% #make dataset with counts data
  add_row(climatic_zone = "polar", n = 0) %>%  #add polar
  # Add category
  mutate(catg="Climatic Zone") %>% 
  # Rename
  rename(habitat=climatic_zone) %>%  #change name of climatic_zone column to habitat so all three dataset can be combined 
  mutate(habitat = recode(habitat, "na" = "global"))

# Habitat counts
habitat_counts <- data %>% 
  count(habitat_type) %>% 
  # Add category
  mutate(catg="Habitat") %>% 
  # Rename
  rename(habitat=habitat_type)

#count assemblages
assemblage_all <- data %>% 
  count(assemblage_type) %>% 
  mutate(proportion = n /sum(n))

#ID unique assemblages
unique_assemblages <- data %>% 
  distinct(assemblage_type)

#create lookup table
#write_csv(unique_assemblages, "unique_assemblages.csv")

#lookup table was then manually editing before being read back in

#read in assemblage lookup table
lookup_table_assembl <- read.csv(here("data", "unique_assemblages_final.csv"))

#combine assemblage data with lookup table, make counts
assemblage_counts <- assemblage_all %>% 
  left_join(lookup_table_assembl, by = "assemblage_type") %>% #join look up table
  select(n, grouped_assemblage_highest) %>% #select highest grouping
  group_by(grouped_assemblage_highest) %>% 
  summarise(n = sum(n), .groups = "drop") %>% 
  ungroup() %>% 
  mutate(catg = "Assemblage") %>% 
  rename(habitat = grouped_assemblage_highest) %>% 
  mutate(habitat = recode(habitat, "na" = "Species-specific"))
```

```{r new figure with mpa counts}
#climatic zone counts
climatic_zone <- data %>% 
  count(climatic_zone, mpa_effect) %>% #make dataset with counts data
  add_row(climatic_zone = "polar", n = 0) %>%  #add polar
  # Add category
  mutate(catg="Climatic Zone") %>% 
  # Rename
  rename(habitat=climatic_zone) %>%  #change name of climatic_zone column to habitat so all three dataset can be combined 
  mutate(habitat = recode(habitat, "na" = "global"))

# Habitat counts
habitat_counts <- data %>% 
  count(habitat_type, mpa_effect) %>% 
  # Add category
  mutate(catg="Habitat") %>% 
  # Rename
  rename(habitat=habitat_type)

#count assemblages
assemblage_all <- data %>% 
  count(assemblage_type, mpa_effect) %>% 
  mutate(proportion = n /sum(n))

#ID unique assemblages
unique_assemblages <- data %>% 
  distinct(assemblage_type)

#create lookup table
#write_csv(unique_assemblages, "unique_assemblages.csv")

#lookup table was then manually editing before being read back in

#read in assemblage lookup table
lookup_table_assembl <- read.csv(here("data", "unique_assemblages_final.csv"))

#combine assemblage data with lookup table, make counts
assemblage_counts <- assemblage_all %>% 
  left_join(lookup_table_assembl, by = "assemblage_type") %>% #join look up table
  select(n, grouped_assemblage_highest, mpa_effect) %>% #select highest grouping
  group_by(grouped_assemblage_highest, mpa_effect) %>% 
  summarise(n = sum(n), .groups = "drop") %>% 
  ungroup() %>% 
  mutate(catg = "Assemblage") %>% 
  rename(habitat = grouped_assemblage_highest) %>% 
  mutate(habitat = recode(habitat, "na" = "Species-specific"))
```


``` {r calculate percentages for paper}
#climatic zone
tropic_total <- climatic_zone[climatic_zone$habitat == "tropical", "n"]
subtropic_total <- climatic_zone[climatic_zone$habitat == "subtropical", "n"]
temperate_total <- climatic_zone[climatic_zone$habitat == "temperate", "n"]
climatic_total <- climatic_zone %>% summarize(total = sum(n))
tropic_percent <- tropic_total/climatic_total
subtropic_percent <- subtropic_total/climatic_total
temperate_percent <- temperate_total/climatic_total

#habitats
habitat_total <- habitat_counts %>% summarize(total = sum(n))
coral_total <- habitat_counts[habitat_counts$habitat == "coral_reef", "n"]
coral_percent <- coral_total/habitat_total
rockyreef_total <- habitat_counts[habitat_counts$habitat == "rocky_reef", "n"]
rockyreef_percent <- rockyreef_total/habitat_total
kelp_total <- habitat_counts[habitat_counts$habitat == "kelp_forest", "n"]
kelp_percent <- kelp_total/habitat_total
```


```{r make combined figure}
# Merge counts
counts <- bind_rows(climatic_zone, habitat_counts, assemblage_counts) %>% 
  # Format category
  mutate(catg=factor(catg, levels=c("Climatic Zone", "Habitat", "Assemblage"))) %>% 
  # mutate(catg = case_when(
  #   catg == "Climatic Zone" ~ "(a) Climatic Zone",
  #   catg == "Habitat" ~ "(b) Habitat",
  #   catg == "Assemblage" ~ "(c) Assemblage"
  # )) %>% 
  # Format habitats
  mutate(habitat=gsub("_", " ", habitat) %>% stringr::str_to_sentence(),
         habitat=recode(habitat, "Na"="Not specified")) %>% 
  mutate(mpa_effect = if_else(is.na(mpa_effect), "no_effect", mpa_effect)) #change NA to "no effect" to drop it from the legend. this should not change the actual graph because the only category with no effect is polar, and there is no data for polar regions

figure2 <- ggplot(counts, aes(x=n, 
                        y=tidytext::reorder_within(habitat, n, catg),
                        fill = mpa_effect)) +
  facet_grid(catg~., space="free_y", scales="free_y", switch = "y") +
  geom_bar(stat="identity") +
  # Labels
  labs(x="Number of occurences", y="", fill = "MPA Effect") +
  # Scales
  tidytext::scale_y_reordered() +
  # Theme
  #theme_classic() +
  my_theme() +
  theme(strip.background = element_rect(colour=NA, fill=NA),
        strip.text = element_text(
          size = 14),
        strip.placement = "outside") +
  scale_fill_manual(values = mpa_colors,
                    labels = c("no_effect" = "No detected effect",
                              "positive_ecosystem" = "Ecosystem (+)", 
                              "negative_ecosystem" = "Ecosystem (-)",
                              "positive_population" = "Population (+)", 
                              "negative_population" = "Population (-)"),
                    breaks = c("no_effect", "positive_ecosystem", "positive_population", "negative_ecosystem", "negative_population"))

figure2

ggsave(here("fig", "figure2_v3.png"), plot = figure2, width = 8, height = 8, dpi = 300)
```


```{r figure for publication}
figure2_v4 <- ggplot(counts, aes(x=n, 
                        y=tidytext::reorder_within(habitat, n, catg),
                        fill = mpa_effect)) +
  facet_grid(catg~., space="free_y", scales="free_y", switch = "y") +
  geom_bar(stat="identity") +
  # Labels
  labs(x="Number of occurences", y="", fill = "MPA Effect",
       caption = stringr::str_wrap(
       "Figure 2: Number of occurrences of each climatic zone type, habitat type, and assemblage type. Each color represents a different MPA effect.", 
       width = 75)) +
  # Scales
  tidytext::scale_y_reordered() +
  # Theme
  #theme_classic() +
  my_theme() +
  scale_fill_manual(values = mpa_colors,
                    labels = c("no_effect" = "No detected effect",
                              "positive_ecosystem" = "Ecosystem (+)", 
                              "negative_ecosystem" = "Ecosystem (-)",
                              "positive_population" = "Population (+)", 
                              "negative_population" = "Population (-)"),
                    breaks = c("no_effect", "positive_ecosystem", "positive_population", "negative_ecosystem", "negative_population")) +
    theme(strip.background = element_rect(colour=NA, fill=NA),
        strip.text = element_text(
          size = 14),
        strip.placement = "outside")

figure2_v4

ggsave(here("fig", "figure2_v4.png"), plot = figure2_v4, width = 9, height = 8, dpi = 900)
```

```{r}
figure2_v5 <- ggplot(counts, aes(x=n, 
                        y=tidytext::reorder_within(habitat, n, catg),
                        fill = mpa_effect)) +
  facet_grid(catg~., space="free_y", scales="free_y", switch = "y") +
  geom_bar(stat="identity") +
  # Labels
  labs(x="Number of occurences", y="", fill = "MPA Effect") +
  # Scales
  tidytext::scale_y_reordered() +
  # Theme
  #theme_classic() +
  my_theme() +
  scale_fill_manual(values = mpa_colors,
                    labels = c("no_effect" = "No detected effect",
                              "positive_ecosystem" = "Ecosystem (+)", 
                              "negative_ecosystem" = "Ecosystem (-)",
                              "positive_population" = "Population (+)", 
                              "negative_population" = "Population (-)"),
                    breaks = c("no_effect", "positive_ecosystem", "positive_population", "negative_ecosystem", "negative_population")) +
    theme(strip.background = element_rect(colour=NA, fill=NA),
        strip.text = element_text(
          size = 14),
        strip.placement = "outside")

figure2_v5

ggsave(here("fig", "figure2_v5.png"), plot = figure2_v5, width = 9, height = 8, dpi = 600)
```

