---
title: "Make Figure 4"
output: html_document
date: "2025-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Get world map data
map_latlong <- data %>% 
  select(climate_effect, mpa_effect, latitude, longitude) %>% 
  mutate(
    jitter_lat = jitter(latitude, amount = 5),
    jitter_long = jitter(longitude, amount = 5)
  )

#horizontal line labels
lines_df <- data.frame(
  y = c(23.4, -23.4, -40, 40, 60, -60),
  label = c("Tropical", "Tropical", "Subtropical", "Subtropical", "Temperate", "Temperate")
)

world_map <- map_data("world")

map_climate <- ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group),
               fill = "gray90", color = NA) +
  geom_point(data = map_latlong, aes(x = jitter_long, y = jitter_lat, color = climate_effect), size = 1.5, alpha = 0.6) +
  coord_fixed(1.3) +  # Keeps aspect ratio of map
  my_theme() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank()) +
  labs(color = "Climate impact") +
  scale_color_manual(values = climate_colors,
                     labels = c("mortality" = "Mortality",
                                "habitat_formation" = "Habitat Formation",
                                "body_size" = "Body Size",
                                "movement_range" = "Movement and range shifts",
                                "disease_parasite" = "Disease and parasitism",
                                "phenology" = "Phenology",
                                "reproduction" = "Reproduction"),
                     breaks = c("mortality", "habitat_formation", "body_size", "movement_range", "disease_parasite", "reproduction", "phenology")) +
  ylim(-65, 90) +
  geom_hline(yintercept = c(23.4, -23.4, 40, -40, 60, -60), linetype = "dashed", color = "grey80") +
  geom_text(data = lines_df,
    aes(x = -155, y = y, label = label),
    hjust = 1,          # right-align the text to the edge
    vjust = -0.3,       # small vertical adjustment
    color = "grey40",
    size = 2.5
  )


map_mpa <- ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group),
               fill = "gray90", color = NA) +
  geom_point(data = map_latlong, aes(x = jitter_long, y = jitter_lat, color = mpa_effect), size = 1.5, alpha = 0.6) +
  coord_fixed(1.3) +  # Keeps aspect ratio of map
  my_theme() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank()) +
  labs(color = "MPA effect") +
  scale_color_manual(values = mpa_colors,
                     labels = c("negative_ecosystem" = "Ecosystem (-)",
                                "negative_population" = "Population (-)",
                                "no_effect" = "No detected effect",
                                "positive_ecosystem" = "Ecosystem (+)",
                                "positive_population" = "Population (+)"),
                     breaks = c("no_effect", "positive_ecosystem", "positive_population", "negative_ecosystem", "negative_population")) +
  ylim(-65, 90) +
  geom_hline(yintercept = c(23.4, -23.4, 40, -40, 60, -60), linetype = "dashed", color = "grey80") +
  geom_text(data = lines_df,
    aes(x = -155, y = y, label = label),
    hjust = 1,          # right-align the text to the edge
    vjust = -0.3,       # small vertical adjustment
    color = "grey40",
    size = 2.5
  )


map_climate
map_mpa
```


```{r, fig.width = 20}
#combine figures using patchwork packages
figure_4 <- map_mpa + map_climate +
  plot_layout(ncol = 1) +
  plot_annotation(tag_levels = list(c("(a)", "(b)")))

#print figure
figure_4

ggsave(here("fig", "figure4.png"), plot = figure_4, width = 12, height = 10, dpi = 300)
```

