---
title: "5_heatmap"
output: html_document
date: "2025-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(viridis)

eco_effects <- data %>% 
  select(mpa_effect, climate_effect) %>% 
  group_by(mpa_effect, climate_effect) %>% 
  count(mpa_effect, climate_effect, name = "count") %>% 
  #normalize by climate impact/column
  group_by(climate_effect) %>% 
  mutate(proportion = count/(sum(count))) %>% 
  ungroup() %>% 
  #normalize by mpa effect
  group_by(mpa_effect) %>% 
  mutate(proportion_row = count/(sum(count))) %>% 
  ungroup()

heatmap_v2 <- ggplot(data = eco_effects, aes(x = climate_effect, y = mpa_effect, fill = count)) +
  geom_tile() +
  labs(
    x = "Climate impact",
    y = "MPA effect",
    fill = "Number of occurrences"
  ) +
  scale_y_discrete(labels = c("positive_population" = "Population (+)", 
                              "positive_ecosystem" = "Ecosystem (+)",
                              "no_effect" = "No detected effect", 
                              "negative_population" = "Population (-)",
                              "negative_ecosystem" = "Ecosystem (-)"),
                   limits = c("negative_population", "negative_ecosystem", "positive_population", "positive_ecosystem", "no_effect")) +
  scale_x_discrete(labels = c("body_size" = "Body Size",
                                 "disease_parasite" = "Disease & Parasitism",
                                 "habitat_formation" = "Habitat Formation",
                                 "mortality" = "Mortality",
                                 "movement_range" = "Movement & Range Shifts",
                                 "phenology" = "Phenology",
                                 "reproduction" = "Reproduction"),
                   limits = c("mortality", "habitat_formation", "body_size", "movement_range", "disease_parasite", "reproduction", "phenology")) +
  # scale_fill_gradient2(low = "grey",
  #                    high = "black") +
  scale_fill_viridis(option = "viridis") +
  my_theme() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.caption = element_text(hjust = 0, margin = margin(t = 5)),
  )

heatmap_v2

#ggsave(here("fig", "figure5.png"), plot = heatmap_v2, width = 8, height = 5, dpi = 300)
```

```{r high resolution}
# heatmap_v3 <- ggplot(data = eco_effects, aes(x = climate_effect, y = mpa_effect, fill = count)) +
#   geom_tile() +
#   labs(
#     x = "Climate impact",
#     y = "MPA effect",
#     fill = "Number of occurrences",
#     caption = stringr::str_wrap(
#        "Figure 5: Number of occurrences for each combination of MPA effect and climate impact. Darker shades indicate a higher observation frequency of each combination.", 
#        width = 75)
#   ) +
#   scale_y_discrete(labels = c("positive_population" = "Population (+)", 
#                               "positive_ecosystem" = "Ecosystem (+)",
#                               "no_effect" = "No detected effect", 
#                               "negative_population" = "Population (-)",
#                               "negative_ecosystem" = "Ecosystem (-)"),
#                    limits = c("negative_population", "negative_ecosystem", "positive_population", "positive_ecosystem", "no_effect")) +
#   scale_x_discrete(labels = c("body_size" = "Body Size",
#                                  "disease_parasite" = "Disease & Parasitism",
#                                  "habitat_formation" = "Habitat Formation",
#                                  "mortality" = "Mortality",
#                                  "movement_range" = "Movement & Range Shifts",
#                                  "phenology" = "Phenology",
#                                  "reproduction" = "Reproduction"),
#                    limits = c("mortality", "habitat_formation", "body_size", "movement_range", "disease_parasite", "reproduction", "phenology")) +
#   # scale_fill_gradient2(low = "grey",
#   #                    high = "black") +
#   scale_fill_viridis(option = "viridis") +
#   my_theme() +
#   theme(
#     axis.text.x = element_text(angle = 45, hjust = 1),
#     plot.caption = element_text(hjust = 0, margin = margin(t = 5)),
#   )
# 
# heatmap_v3
# 
# ggsave(here("fig", "figure5_v1.png"), plot = heatmap_v3, width = 8, height = 6, dpi = 900)
```

```{r}
heatmap_v4 <- ggplot(data = eco_effects, aes(x = climate_effect, y = mpa_effect, fill = count)) +
  geom_tile() +
  labs(
    x = "Climate impact",
    y = "MPA effect",
    fill = "Number of occurrences") +
  scale_y_discrete(labels = c("positive_population" = "Population (+)", 
                              "positive_ecosystem" = "Ecosystem (+)",
                              "no_effect" = "No detected effect", 
                              "negative_population" = "Population (-)",
                              "negative_ecosystem" = "Ecosystem (-)"),
                   limits = c("negative_population", "negative_ecosystem", "positive_population", "positive_ecosystem", "no_effect")) +
  scale_x_discrete(labels = c("body_size" = "Body Size",
                                 "disease_parasite" = "Disease & Parasitism",
                                 "habitat_formation" = "Habitat Formation",
                                 "mortality" = "Mortality",
                                 "movement_range" = "Movement & Range Shifts",
                                 "phenology" = "Phenology",
                                 "reproduction" = "Reproduction"),
                   limits = c("mortality", "habitat_formation", "body_size", "movement_range", "disease_parasite", "reproduction", "phenology")) +
  # scale_fill_gradient2(low = "grey",
  #                    high = "black") +
  scale_fill_viridis(option = "viridis") +
  my_theme() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.caption = element_text(hjust = 0, margin = margin(t = 5)),
  )

heatmap_v4

ggsave(here("fig", "figure5_v2.png"), plot = heatmap_v4, width = 8, height = 6, dpi = 900)
```

