---
title: "Figure 6"
output: html_document
date: "2025-09-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mpa_effects_by_habitat <- data %>% 
  select(climatic_zone, habitat_type, climate_effect, mpa_effect) %>% 
  #remove NAs
  filter(!mpa_effect == "not_assessed") %>% 
  filter(!climatic_zone == "na") %>% 
  filter(!habitat_type == "na") %>% 
  #count by category
  group_by(climatic_zone, habitat_type) %>% 
  count(mpa_effect) %>% 
  mutate(proportion = n /sum(n)) %>% 
  #format habitat type names
   mutate(habitat_type=gsub("_", " ", habitat_type) %>% stringr::str_to_sentence(),
          habitat_type=recode(habitat_type, "Na"="Not specified")) %>% 
  #format climatic zone names
  mutate(climatic_zone = str_to_sentence(climatic_zone))

#reorder climatic_zone factors to tropical, subtropical, temperate
mpa_effects_by_habitat$climatic_zone <- factor(mpa_effects_by_habitat$climatic_zone, levels = c("Tropical", "Subtropical", "Temperate"))

#calculate counts and percents of MPA effects by climate zone
mpa_effects_zone <- data %>% 
  select(climatic_zone, mpa_effect) %>% 
  mutate(mpa_effect = case_when(
    mpa_effect == "negative_ecosystem" ~ "negative",
    mpa_effect == "negative_population" ~ "negative",
    mpa_effect == "positive_population" ~ "positive",
    mpa_effect == "positive_ecosystem" ~ "positive",
    TRUE ~ mpa_effect
  )) %>% 
  #remove NAs
  filter(!climatic_zone == "na") %>% 
  #count by category
  group_by(climatic_zone) %>% 
  count(mpa_effect) %>% 
  mutate(proportion = n /sum(n)) %>% 
  ungroup()

#calculate counts and percents of MPA effects by habitat type
mpa_effects_habitat <- data %>% 
  select(habitat_type, mpa_effect) %>% 
  mutate(mpa_effect = case_when(
    mpa_effect == "negative_ecosystem" ~ "negative",
    mpa_effect == "negative_population" ~ "negative",
    mpa_effect == "positive_population" ~ "positive",
    mpa_effect == "positive_ecosystem" ~ "positive",
    TRUE ~ mpa_effect
  )) %>% 
  #remove NAs
  filter(!habitat_type == "na") %>% 
  #count by category
  group_by(habitat_type) %>% 
  count(mpa_effect) %>% 
  mutate(proportion = n /sum(n)) %>% 
  ungroup()
  

figure_6 <- ggplot(data = mpa_effects_by_habitat, aes(fill = mpa_effect, y = n, x = habitat_type)) + 
  facet_wrap(climatic_zone~.) +
  geom_bar(position = 'stack', stat = 'identity') + 
  theme_classic() +
  labs(
    fill = "MPA Effect",
    y = "Number of Occurrences",
    x = "Habitat Type"
  ) +
  my_theme() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_fill_manual(values = mpa_colors,
                    labels = c("no_effect" = "No effect",
                              "positive_ecosystem" = "Ecosystem (+)", 
                              "negative_ecosystem" = "Ecosystem (-)",
                              "positive_population" = "Population (+)", 
                              "negative_population" = "Population (-)"),
                    breaks = c("no_effect", "positive_ecosystem", "positive_population", "negative_ecosystem", "negative_population")) +
    theme(strip.background = element_rect(colour=NA, fill=NA),
        strip.text = element_text(
          size = 14
        ))

figure_6
```

